export default {
  APPWRITE: {
    BASE_URL: import.meta.env.VITE_APPWRITE_BASE_URL,
    PROJECT_ID: import.meta.env.VITE_APPWRITE_PROJECT_ID,
    GUESTS: {
      DATABASE_ID: import.meta.env.VITE_APPWRITE_DATABASE_GUESTS_ID,
      GUEST_COLLECTION_ID: import.meta.env.VITE_APPWRITE_DATABASE_GUESTS_GUEST_ID,
      GUEST_GROUP_COLLECTION_ID: import.meta.env.VITE_APPWRITE_DATABASE_GUESTS_GUEST_GROUP_ID,
    },
    QUESTIONS: {
      DATABASE_ID: import.meta.env.VITE_APPWRITE_DATABASE_QUESTIONS_ID,
      COLLECTION_ID: import.meta.env.VITE_APPWRITE_DATABASE_QUESTIONS_QUESTION_ID,
    },
    FUNCTIONS: {
      CREATE_GUEST_FUNCTION_ID: import.meta.env.VITE_CREATE_GUEST_FUNCTION_ID,

      CREATE_GUEST_GROUP_FUNCTION_ID: import.meta.env.VITE_CREATE_GUEST_GROUP_FUNCTION_ID,
      GET_GUEST_GROUPS_FUNCTION_ID: import.meta.env.VITE_GET_GUEST_GROUPS_FUNCTION_ID,
      UPDATE_GUEST_GROUP_FUNCTION_ID: import.meta.env.VITE_UPDATE_GUEST_GROUP_FUNCTION_ID,
      DELETE_GUEST_GROUP_FUNCTION_ID: import.meta.env.VITE_DELETE_GUEST_GROUP_FUNCTION_ID,

      UPDATE_QUESTIONIRE_FUNCTION_ID: import.meta.env.VITE_UPDATE_QUESTIONIRE_FUNCTION_ID,
    },
  },
};
